name: Deploy to VPS

on:
  push:
    branches:
      - main # or your deployment branch

env:
  TELEGRAM_BOT_OWNER_ID: ${{ secrets.TELEGRAM_BOT_OWNER_ID }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  SPOTIFY_API_URL: ${{ secrets.SPOTIFY_API_URL }}
  SPOTIFY_ACCOUNT_URL: ${{ secrets.SPOTIFY_ACCOUNT_URL }}
  SPOTIFY_REDIRECT_URI: ${{ secrets.SPOTIFY_REDIRECT_URI }}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  SPOTIFY_TOKEN_API_URL: ${{ secrets.SPOTIFY_TOKEN_API_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # - name: Install dependencies
      #   run: npm install

      - name: Install PM2
        run: npm install -g pm2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
            nvm use 22

            cd ${{ secrets.VPS_PATH }}
            git pull origin main
            npm install
            pm2 restart all || pm2 start index.js --name sypotify
          EOF
